import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteWrapper from "./RouteWrapper";
import { ReduxProvider } from "./provider";
import { Toaster } from "react-hot-toast";
import TopLoaderClient from "./TopLoader";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AutoLeaveTracker from "@/components/dashboard/user-dashboard/AutoLeaveTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skyborne",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <TopLoaderClient />
          <ReduxProvider>
            <RouteWrapper>
            <AutoLeaveTracker/>
              {children}
              <Toaster position="top-right" />
            </RouteWrapper>
          </ReduxProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
